apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    component: frontend
    environment: dev
  annotations:
    imageregistry: "https://hub.docker.com/"
    jenkinsURL: "http://jenkins.roboshop.internal"  
spec:
  containers:
  - name: nginx
    image: nginx  