apiVersion: v1
kind: Pod
metadata:
  name: resources
  namespace: roboshop 
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
    #soft limit, if the container exceeds this limit, it will be throttled
      requests:
        memory: "64Mi"

      #hard limit, if the container exceeds this limit, it will be killed   
      limits:
        memory: "128Mi"
        cpu: "500m"