apiVersion: v1
kind: pod
metadata:
  name: env-demo
spec:
  containers:
  - name: env-demo
    image: nginx
    env:
    - name: ENVIRONMENT
      value: roboshop
    - name: LOG_LEVEL
      value: debug    
    - name: devops practices    
      value: "Devops is a culture, not a tool"
      