apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-demo
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef: #We have created our config file, now let’s inject it into a pod definition file
        name: nginx-config-prem #08-confimap metadata name I have gien here
