apiVersion: v1
kind: pod
metadata: 
  name: svc-test
  namespace: roboshop
spec:
  containers:
  - name:  almalinux
    image: almalinux
    comand: ["sleep", "1000"]
    ports:
    - containerPort: 80  
