apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
  #labels are used to select the pods for which this service will be created
    project: roboshop
    component: frontend
    environment: dev
ports:
  - protocol: TCP 
    port: 80 #port on which the service will be exposed
    targetPort: 80 #container port to which the traffic will be forwarded