apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-replicaset
  labels:
    project: roboshop
    purpose: replicaset-demo
    component: frontend
    environment: dev
    tier: web
  annotations:
    kubernetes.io/change-cause: "Updated the deployment to 1.29" 

spec:
  replicas: 2

  selector:
    matchLabels:
      project: roboshop
      purpose: replicaset-demo
      component: frontend
      environment: dev
      tier: web

  template:
    metadata:
      labels:
        project: roboshop
        purpose: replicaset-demo
        component: frontend
        environment: dev
        tier: web

    spec:
      containers:
      - name: nginx
        image: nginx:1.29
      
        